AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0230bd60aa48260c6"  # Specify the AMI ID for your desired Amazon Machine Image
      InstanceType: "t2.micro"
      KeyName: "cfkeypair"  # Specify the key pair for SSH access
